# Ejemplo statefulset kubernetes

# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-example
  labels:
    app: statefulset-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: statefulset-example
  serviceName: statefulset-example
  template:
    metadata:
      labels:
        app: statefulset-example
    spec:
      containers:
      # Nginx
      - name: nginx
        image: nginx:1.27.4
        ports:
        - containerPort: 80
      # MySQL
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: database
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      # PhpMyAdmin
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - containerPort: 8080
        env:
        - name: PMA_HOST
          value: statefulset-example
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: APACHE_PORT
          value: "8080"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

# Headless Service para el StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: statefulset-example
  labels:
    app: statefulset-example
spec:
  clusterIP: None
  selector:
    app: statefulset-example
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  - name: phpmyadmin-port
    protocol: TCP
    port: 8080
    targetPort: 8080

# ---

# # Service para exponer MySQL y PhpMyAdmin a localhost
# apiVersion: v1
# kind: Service
# metadata:
#   name: statefulset-nodeport
#   labels:
#     app: statefulset-example
# spec:
#   type: NodePort
#   selector:
#     app: statefulset-example
#   ports:
#   - name: nginx
#     protocol: TCP
#     port: 80
#     targetPort: 80
#     nodePort: 30000  # Puerto expuesto en el nodo
#   - name: mysql
#     protocol: TCP
#     port: 3306
#     targetPort: 3306
#     nodePort: 30036  # Puerto expuesto en el nodo
#   - name: phpmyadmin
#     protocol: TCP
#     port: 8080
#     targetPort: 8080
#     nodePort: 30080  # Puerto expuesto en el nodo

---

# Service para balancear la carga entre los pods
apiVersion: v1
kind: Service
metadata:
  name: statefulset-loadbalancer
  labels:
    app: statefulset-example
spec:
  type: LoadBalancer
  selector:
    app: statefulset-example
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  - name: phpmyadmin
    protocol: TCP
    port: 8080
    targetPort: 8080